development:
  adapter: sqlite3
  encoding: unicode
  database: booze-boodega
  host: localhost
  pool: 5
  username: "sqlite3"
  password: kwish@12
production:
  adapter: sqlite3
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>